---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "linstorversion.internal.linstor.linbit.com"
spec:
  group: "internal.linstor.linbit.com"
  versions:
  - name: "v1" # hopefully never changes
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              version:
                type: "integer"
                format: "int32"
  scope: "Cluster"
  names:
    plural: "linstorversion"
    singular: "linstorversion"
    kind: "LinstorVersion"
