---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "rollback.internal.linstor.linbit.com"
spec:
  group: "internal.linstor.linbit.com"
  versions:
  - name: "v1" # hopefully never changes
    served: true
    storage: true
    additionalPrinterColumns:
    - jsonPath: '.spec'
      name: Spec
      type: string
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              rollback_map:
                 type: "object"
                 x-kubernetes-preserve-unknown-fields: true
              delete_map:
                 type: object
                 additionalProperties:
                    type: array
                    items:
                       type: string
            required:
              - rollback_map
              - delete_map
        required:
          - spec
  scope: "Cluster"
  names:
    plural: "rollback"
    singular: "rollback"
    kind: "Rollback"
