name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t hello-world-app .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag hello-world-app ${{ secrets.DOCKER_REGISTRY }}/hello-world-app
          docker push ${{ secrets.DOCKER_REGISTRY }}/hello-world-app

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster backstage-cluster --service myecs-service --force-new-deployment
