---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "nodenetinterfaces.internal.linstor.linbit.com"
spec:
  group: "internal.linstor.linbit.com"
  versions:
  - name: "v1-15-0"
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              uuid:
                type: "string"
              node_name:
                type: "string"
              node_net_name:
                type: "string"
              node_net_dsp_name:
                type: "string"
              inet_address:
                type: "string"
              stlt_conn_port:
                type: "integer"
              stlt_conn_encr_type:
                type: "string"
  scope: "Cluster"
  names:
    plural: "nodenetinterfaces"
    singular: "nodenetinterfaces"
    kind: "NodeNetInterfaces"
