---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "satellitescapacity.internal.linstor.linbit.com"
spec:
  group: "internal.linstor.linbit.com"
  versions:
  - name: "v1-15-0"
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              node_name:
                type: "string"
              capacity:
                type: "string"
                format: "byte"
              fail_flag:
                type: "boolean"
  scope: "Cluster"
  names:
    plural: "satellitescapacity"
    singular: "satellitescapacity"
    kind: "SatellitesCapacity"
