---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "sectyperules.internal.linstor.linbit.com"
spec:
  group: "internal.linstor.linbit.com"
  versions:
  - name: "v1-15-0"
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              domain_name:
                type: "string"
              type_name:
                type: "string"
              access_type:
                type: "integer"
  scope: "Cluster"
  names:
    plural: "sectyperules"
    singular: "sectyperules"
    kind: "SecTypeRules"
