name: Build DEB Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-22.04]
        include:
          - os: ubuntu-22.04
            dist: Nobel
          - os: ubuntu-22.04
            dist: jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache APT packages
        uses: actions/cache@v2
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/build.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Set up APT
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts debhelper dh-make

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            devscripts \
            debhelper \
            dh-make \
            build-essential \
            libssl-dev \
            libxml2-dev \
            libcurl4-openssl-dev \
            libtool \
            autoconf \
            automake \
            libglib2.0-dev \
            python3-dev \
            python3-setuptools \
            python3-pip \
            ruby \
            rubygems

      - name: Build DRBD Reactor
        run: |
          cd src/drbd-reactor
          chmod +x autogen.sh
          ./autogen.sh
          ./configure
          make
          make deb

      - name: Build DRBD
        run: |
          cd src/drbd
          ./autogen.sh
          ./configure
          make
          make deb

      - name: Build DRBD Utils
        run: |
          cd src/drbd-utils
          ./autogen.sh
          ./configure
          make
          make deb

      - name: Build LINSTOR Server
        run: |
          cd src/linstor-server
          ./autogen.sh
          ./configure
          make
          make deb

      - name: Build LINSTOR PyAPI
        run: |
          cd src/linstor-pyapi
          python3 setup.py sdist bdist_deb

      - name: Build LINSTOR Client
        run: |
          cd src/linstor-client
          ./autogen.sh
          ./configure
          make
          make deb

      - name: Build LINSTOR Gateway
        run: |
          cd src/linstor-gateway
          ./autogen.sh
          ./configure
          make
          make deb

      - name: Upload DEB Packages
        uses: actions/upload-artifact@v2
        with:
          name: deb-packages
          path: |
            src/drbd-reactor/*.deb
            src/drbd/*.deb
            src/drbd-utils/*.deb
            src/linstor-server/*.deb
            src/linstor-pyapi/dist/*.deb
            src/linstor-client/*.deb
            src/linstor-gateway/*.deb
