name: Build and Publish DRBD Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up APT
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            devscripts \
            debhelper \
            dh-make \
            build-essential \
            libssl-dev \
            libxml2-dev \
            libcurl4-openssl-dev \
            libtool \
            autoconf \
            automake \
            libglib2.0-dev \
            python3-dev \
            python3-setuptools \
            python3-pip

      - name: Clone DRBD repository
        run: |
          git clone https://github.com/LINBIT/drbd.git
          cd drbd
          git checkout -b build-branch

      - name: Generate configuration files
        run: |
          cd drbd
          ./autogen.sh

      - name: Configure and build package
        run: |
          cd drbd
          ./configure
          make
          sudo make install
          make deb

      - name: Install PackageCloud CLI
        run: |
          sudo gem install package_cloud

      - name: Publish package to PackageCloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
          package_cloud push your_packagecloud_username/repository/ubuntu/jammy src/drbd/*.deb
