name: Build and Deploy LINBIT Packages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sourcepackage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        project: [drbd-reactor, drbd, drbd-utils, linstor-server, linstor-py-api, linstor-client, linstor-gateway]

    outputs:
      VERSION: ${{ steps.set_version.outputs.version }}
      PRERELEASE_TAG: ${{ steps.set_version.outputs.prerelease_tag }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set version and pre-release tag
      id: set_version
      run: |
        VERSION=$(date +%Y%m%d%H%M%S)
        echo "::set-output name=version::$VERSION"
        echo "::set-output name=prerelease_tag::alpha"

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y \
          build-essential \
          debhelper \
          devscripts \
          dh-make \
          lintian \
          ruby-dev \
          cargo \
          rustc \
          bash-completion \
          git

    - name: Build source package
      run: |
        cd ${{ matrix.project }}
        debuild -D -sa -Zxz

    - name: Store source package
      uses: actions/upload-artifact@v3.1.0
      with:
        name: my-srcpkg-${{ matrix.project }}
        path: ../*.dsc

  binary_packages:
    name: Build binary packages
    needs: sourcepackage
    strategy:
      fail-fast: true
      matrix:
        dist: [jammy, noble]
        arch: [amd64]
        project: [drbd-reactor, drbd, drbd-utils, linstor-server, linstor-py-api, linstor-client, linstor-gateway]

    runs-on: ubuntu-latest

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3.0.0
      with:
        name: my-srcpkg-${{ matrix.project }}
        path: artifacts/${{ matrix.project }}

    - name: Build
      uses: sillsdev/gha-ubuntu-packaging@v0.9
      with:
        dist: "${{ matrix.dist }}"
        platform: "${{ matrix.arch }}"
        source_dir: "artifacts/${{ matrix.project }}"
        sourcepackage: "my${{ needs.sourcepackage.outputs.VERSION }}-1.dsc"
        prerelease_tag: ${{ needs.sourcepackage.outputs.PRERELEASE_TAG }}

    - name: Store binary packages
      uses: actions/upload-artifact@v3.1.0
      with:
        name: my-binarypkgs-${{ matrix.project }}
        path: |
          artifacts/*
          !artifacts/${{ matrix.project }}/

  deb_signing:
    name: Sign source and binary packages
    needs: [sourcepackage, binary_packages]
    runs-on: ubuntu-latest
    environment: deploy
    strategy:
      fail-fast: true
      matrix:
        project: [drbd-reactor, drbd, drbd-utils, linstor-server, linstor-py-api, linstor-client, linstor-gateway]

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3.0.0
      with:
        name: my-srcpkg-${{ matrix.project }}
        path: artifacts/srcpkg/${{ matrix.project }}

    - name: Download Binary Packages
      uses: actions/download-artifact@v3.0.0
      with:
        name: my-binarypkgs-${{ matrix.project }}
        path: artifacts/binpkg/${{ matrix.project }}

    - name: Sign packages
      uses: sillsdev/gha-deb-signing@v0.6
      with:
        src-pkg-name: "my${{ needs.sourcepackage.outputs.VERSION }}-1_source.changes"
        bin-pkg-name: "my${{ needs.sourcepackage.outputs.VERSION }}-1${{ needs.sourcepackage.outputs.PRERELEASE_TAG }}+"
        artifacts-prefix: "my-${{ matrix.project }}-"
        artifacts-result-name: "my-${{ matrix.project }}-signedpkgs"
        gpg-signing-key: "${{ secrets.GPG_SIGNING_KEY }}"
        debsign-keyid: "${{ secrets.DEBSIGN_KEYID }}"
