name: Build and Publish DRBD-Utils Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: ["noble", "jammy"]
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up APT
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            devscripts \
            debhelper \
            dh-make \
            build-essential \
            libssl-dev \
            libxml2-dev \
            libcurl4-openssl-dev \
            libtool \
            autoconf \
            automake \
            libglib2.0-dev \
            python3-dev \
            python3-setuptools \
            python3-pip \
            coccinelle \
            fakeroot \
            dkms \
            cargo \
            rustc

      - name: Clone DRBD-utils repository
        run: |
          git clone https://github.com/LINBIT/drbd-utils.git
          cd drbd-utils
          git pull

      - name: Generate configuration files
        run: |
          cd drbd-utils
          if [ -f autogen.sh ]; then
            ./autogen.sh || true
          fi
          if [ -f configure ]; then
            ./configure || true
          fi
        
      - name: Verify Makefile existence
        run: |
          cd drbd-utils
          ls -la
          if [ ! -f Makefile ]; then
            echo "Makefile not found!"
            exit 1
          fi

      - name: Build package
        run: |
          cd drbd-utils
          make
          sudo make install
      
      - name: Build Source Package
        run: |
          cd drbd-utils
          dpkg-buildpackage -us -uc -S
      
      - name: Build Binary Package
        run: |
          cd drbd-utils
          dpkg-buildpackage -us -uc -b 

      - name: Install PackageCloud CLI
        run: |
          sudo gem install package_cloud

      - name: Publish package to PackageCloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
          package_cloud push https://packagecloud.io/dniasoff/qcp-linstor-dev/package/ubuntu/${{ matrix.os }} src/drbd/*.deb
