name: Build DRBD Utils

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper xsltproc flex bison curl

    - name: Download and extract DRBD 9 source
      run: |
        curl -LO https://pkg.linbit.com//downloads/drbd/9/drbd-9.1.7.tar.gz
        tar xf drbd-9.1.7.tar.gz
        cd drbd-9.1.7
        make
        sudo make install
        sudo modprobe drbd

    - name: Download and extract DRBD Utils source
      run: |
        curl -LO https://pkg.linbit.com//downloads/drbd/utils/drbd-utils-9.21.1.tar.gz
        tar xf drbd-utils-9.21.1.tar.gz
        cd drbd-utils-9.21.1
        ./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc
        make
        sudo make install
