name: Build and Publish DRBD-Utils Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: ["jammy"]
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive

      - name: Set up APT
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            devscripts \
            debhelper \
            dh-make \
            build-essential \
            libssl-dev \
            libxml2-dev \
            libcurl4-openssl-dev \
            libtool \
            autoconf \
            automake \
            libglib2.0-dev \
            python3-dev \
            python3-setuptools \
            python3-pip \
            coccinelle \
            fakeroot \
            dkms \
            cargo \
            rustc \
            keyutils

      - name: Use local DRBD-utils repository
        run: |
          cd src/drbd-utils
          ./configure --enable-spec
          # or use specific configure parameters
          # ./configure --without-84support --without-drbdmon --with-windrbd --without-manual --prefix=/cygdrive/c/windrbd/usr --localstatedir=/cygdrive/c/windrbd/var --sysconfdir=/cygdrive/c/windrbd/etc
          make
          sudo make install
          
      - name: Build package
        run: |
          cd src/drbd-utils
          make
          sudo make install
      
      - name: Build Source Package
        run: |
          cd src/drbd-utils
          dpkg-buildpackage -us -uc -S
      
      - name: Build Binary Package
        run: |
          cd src/drbd-utils
          dpkg-buildpackage -us -uc -b 

      - name: Install PackageCloud CLI
        run: |
          sudo gem install package_cloud

      - name: Publish package to PackageCloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
          package_cloud push https://packagecloud.io/dniasoff/qcp-linstor-dev/package/ubuntu/${{ matrix.os }} src/drbd/*.deb
