name: Build and Publish DRBD-Utils Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: ["jammy"]

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up APT
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          git \
          build-essential \
          debhelper \
          dkms \
          docbook-xsl \
          help2man \
          python-all \
          python3-dev \
          python3-pip \
          xsltproc \
          flex \
          gcc \
          make \
          autoconf \
          automake \
          coccinelle \
          keyutils \
          libkeyutils-dev \
          xmlto \
          asciidoctor \
          po4a \
          man-db \
          asciidoc

      - name: Clone DRBD Package
        run: |
          git clone https://github.com/LINBIT/drbd.git
          cd drbd
          git submodule update --init --recursive
          make clean all
          sudo make install
        shell: /usr/bin/bash -e {0}
      
      - name: Clone DRBD-utils Package
        run: |
          git clone https://github.com/LINBIT/drbd-utils.git
        shell: /usr/bin/bash -e {0}
      
      - name: Build DRBD Utils Package
        run: |
          cd drbd-utils
          ./autogen.sh
          ./configure
          make -j4
          
        shell: /usr/bin/bash -e {0}
        
      - name: Build Debian Package
        run: |
          cd drbd-utils
          dpkg-buildpackage -rfakeroot -b -uc
        shell: /usr/bin/bash -e {0}

      - name: Install PackageCloud CLI
        run: |
          sudo gem install package_cloud

      - name: Publish package to PackageCloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
          package_cloud push dniasoff/qcp-linstor-dev/package/ubuntu/${{ matrix.os }} ../*.deb
