name: Build and Publish DRBD-Reactor Package

on:
  push:
   branches:
     - main
  pull_request:
   branches:
     - main

jobs:
  build:
    strategy:
      matrix:
        os: ["jammy"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up APT
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            devscripts \
            debhelper \
            dh-make \
            build-essential \
            libssl-dev \
            libxml2-dev \
            libcurl4-openssl-dev \
            libtool \
            autoconf \
            automake \
            libglib2.0-dev \
            python3-dev \
            python3-setuptools \
            python3-pip \
            coccinelle \
            fakeroot \
            dkms \
            cargo \
            rustc

      - name: Build drbd-reactor repository
        run: |
          git clone https://github.com/LINBIT/drbd-reactor.git
          cd drbd-reactor
          make 
          sudo make install
        shell: /usr/bin/bash -e {0}

      - name: Build Package
        run: |
          cd drbd-reactor
          dpkg-buildpackage -us -uc -b

      - name: Install PackageCloud CLI
        run: |
          sudo gem install package_cloud

      - name: Publish package to PackageCloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
          package_cloud push your_packagecloud_username/repository/ubuntu/${{ matrix.os }} ../*.deb
