name: Build and Publish DRBD-Utils Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: ["jammy"]

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up APT
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          devscripts \
          debhelper \
          dh-make \
          build-essential \
          libssl-dev \
          libxml2-dev \
          libcurl4-openssl-dev \
          libtool \
          autoconf \
          automake \
          libglib2.0-dev \
          python3-dev \
          python3-setuptools \
          python3-pip \
          coccinelle \
          fakeroot \
          dkms \
          cargo \
          rustc \
          keyutils \
          xsltproc \
          help2man \
          dh-python \
          docbook-xsl \
          python3-all \
          equivs \
          aspcud \
          dh-virtualenv \
          debmake \
          default-jdk-headless \
          unzip 

      - name: Make DRBD-utils repository
        run: |
          git clone https://github.com/LINBIT/drbd-utils.git
          cd drbd-utils
          make tools
          sudo make install
        shell: /usr/bin/bash -e {0}
      
      # - name: Build Source Package
      #   run: |
      #     cd src/drbd-utils
      #     dpkg-buildpackage -us -uc -S
      
      - name: Build Binary Package
        run: |
          cd drbd-utils
          dpkg-buildpackage -us -uc -b 

      - name: Install PackageCloud CLI
        run: |
          sudo gem install package_cloud

      - name: Publish package to PackageCloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
          package_cloud push dniasoff/qcp-linstor-dev/package/ubuntu/${{ matrix.os }} ../*.deb
