name: Build and Publish Linstor-api-py Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: ["jammy"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
    
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install python-linstor

      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive

      - name: Set up APT
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          devscripts \
          debhelper \
          dh-make \
          build-essential \
          libssl-dev \
          libxml2-dev \
          libcurl4-openssl-dev \
          libtool \
          autoconf \
          automake \
          libglib2.0-dev \
          python3-dev \
          python3-setuptools \
          python3-pip \
          coccinelle \
          fakeroot \
          dkms \
          cargo \
          rustc \
          keyutils \
          xsltproc \
          help2man \
          dh-python \
          docbook-xsl \
          python3-all \
          equivs \
          aspcud \
          dh-virtualenv \
          debmake

      - name: Build and Install linstor-api-py repository
        run: |
          cd src/linstor-api-py
          python3 setup.py build
          python3 setup.py install
          make -C linstor-common cleanpython
      
      - name: Create upstream tarball
        run: |
          cd src
          tar -czf python-linstor-1.22.0.orig.tar.gz linstor-api-py/
          mv python-linstor-1.22.0.orig.tar.gz ../python-linstor-1.22.0.tar.gz
          mv linstor-api-py ../python-linstor-1.22.0

      - name: Build Binary Package
        run: |
          cd src/../python-linstor-1.22.0
          debmake  -b":python"  
          dpkg-buildpackage -us -uc -b  

      - name: Install PackageCloud CLI
        run: |
          sudo gem install package_cloud

      - name: Publish package to PackageCloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
         package_cloud push dniasoff/qcp-linstor-dev/package/ubuntu/${{ matrix.os }}/*.deb
