name: Build and Publish Linstor-Client Package

on:
  push:
   branches:
     - main
  pull_request:
   branches:
     - main

jobs:
  build:
    strategy:
      matrix:
        os: ["jammy"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          python-version: '3.x'
    
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install python-linstor

      - name: Set up APT
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            devscripts \
            debhelper \
            dh-make \
            build-essential \
            libssl-dev \
            libxml2-dev \
            libcurl4-openssl-dev \
            libtool \
            autoconf \
            automake \
            libglib2.0-dev \
            python3-dev \
            python3-setuptools \
            python3-pip \
            coccinelle \
            fakeroot \
            dkms \
            cargo \
            rustc \
            keyutils \
            xsltproc \
            help2man \
            dh-python \
            docbook-xsl \
            python3-all \
            equivs \
            aspcud
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
    
      # - name: Install Python dependencies
      #   run: |
      #       python -m pip install --upgrade pip
      #       pip install setuptools
      #       pip install python-linstor
      # - name: Create and install build dependencies
      #   run: |
      #     cd src/linstor-client
      #     mk-build-deps --install --remove --tool 'apt-cudf-get --solver aspcud -o APT::Get::Assume-Yes=1 -o Debug::pkgProblemResolver=0 -o APT::Install-Recommends=0' debian/control

      - name: local LINSTOR API Py repository
        run: |
          cd src/linstor-api-py
          make 
          python3 setup.py build
          sudo python3 setup.py install

      - name: Local Linstor-Client repository
        run: |
          cd src/linstor-client
          python3 setup.py build_man 
      
      - name: Create upstream tarball
        run: |
          cd src
          tar -czf linstor-client_1.22.1.orig.tar.gz linstor-client/
          mv linstor-client_1.22.1.orig.tar.gz linstor-client/
      
      - name: Build  Package
        run: |
          cd src/linstor-client
          dpkg-buildpackage -us -uc -S
        #  dpkg-buildpackage -d -us -uc -b

      - name: Install PackageCloud CLI
        run: |
          sudo gem install package_cloud

      - name: Publish package to PackageCloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
         package_cloud push https://packagecloud.io/dniasoff/qcp-linstor-dev/package/ubuntu/${{ matrix.os }} src/drbd/*.deb
