name: Build and Publish Linstor-api-py Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: ["noble", "jammy"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up APT
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            devscripts \
            debhelper \
            dh-make \
            build-essential \
            libssl-dev \
            libxml2-dev \
            libcurl4-openssl-dev \
            libtool \
            autoconf \
            automake \
            libglib2.0-dev \
            python3-dev \
            python3-setuptools \
            python3-pip \
            coccinelle \
            fakeroot \
            dkms \
            cargo \
            rustc

      - name: Clone linstor-api-py repository
        run: |
          git clone https://github.com/LINBIT/linstor-api-py.git
          cd linstor-api-py
          git pull

      - name: Build LINSTOR API Py package
        run: |
          cd linstor-api-py
          make -C linstor-common || true  # Attempt to make in linstor-common, allowing failure
          python3 setup.py build

      - name: Install LINSTOR API Py package
        run: |
          cd linstor-api-py
          sudo python3 setup.py install
      
      - name: Build Source Package
        run: |
          cd linstor-api-py
          dpkg-buildpackage -us -uc -S

      - name: Build Binary Package
        run: |
          cd instor-api-py
          dpkg-buildpackage -us -uc -b   

      - name: Install PackageCloud CLI
        run: |
          sudo gem install package_cloud

      - name: Publish package to PackageCloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
         package_cloud push https://packagecloud.io/dniasoff/qcp-linstor-dev/package/ubuntu/${{ matrix.os }} src/drbd/*.deb
