name: Build and Publish Linstor-Gateway Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [noble, jammy]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up APT
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            devscripts \
            debhelper \
            dh-make \
            build-essential \
            libssl-dev \
            libxml2-dev \
            libcurl4-openssl-dev \
            libtool \
            autoconf \
            automake \
            libglib2.0-dev \
            python3-dev \
            python3-setuptools \
            python3-pip \
            coccinelle \
            fakeroot \
            dkms

      - name: Clone DRBD repository
        run: |
          git clone https://github.com/LINBIT/linstor-gateway.git
          cd linstor-gateway
          git pull

      - name: Generate configuration files
        run: |
          cd linstor-gateway
          if [ -f ./configure ]; then
            echo "Configure script found, running configure."
            ./configure
          else
            echo "Configure script not found, checking for other setup scripts."
            # Add additional setup steps here if necessary
          fi

      - name: Build package
        run: |
          cd linstor-gateway
          make
          sudo make install
      
      - name: Build DEB Package
        run: |
          cd linstor-gateway
          dpkg-buildpackage -us -uc -b

      - name: Install PackageCloud CLI
        run: |
          sudo gem install package_cloud

      - name: Publish package to PackageCloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
         package_cloud push https://packagecloud.io/dniasoff/qcp-linstor-dev/package/ubuntu/${{ matrix.os }} src/drbd/*.deb
