name: Build and Publish Linstor-Gateway Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: ["jammy"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up APT
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          devscripts \
          debhelper \
          dh-make \
          build-essential \
          libssl-dev \
          libxml2-dev \
          libcurl4-openssl-dev \
          libtool \
          autoconf \
          automake \
          libglib2.0-dev \
          python3-dev \
          python3-setuptools \
          python3-pip \
          coccinelle \
          fakeroot \
          dkms \
          cargo \
          rustc \
          keyutils \
          xsltproc \
          help2man \
          dh-python \
          docbook-xsl \
          python3-all \
          equivs \
          aspcud \
          dh-virtualenv \
          debmake \
          default-jdk-headless \
          unzip 
    
      - name: Build and Install LINSTOR API Py package
        run: |
          cd src/linstor-api-py
          make -C linstor-common || true 
          python3 setup.py build
          sudo python3 setup.py install
    
      - name: Build and Install LINSTOR Client package
        env:
          PYTHONPATH: "../linstor-api-py:."
        run: |
          cd src/linstor-client
          python3 setup.py build_man
          sudo python3 setup.py install
    
      - name: Build and Package LINSTOR Gateway
        run: |
          cd src/linstor-gateway
          dpkg-buildpackage -us -uc -b
    
      - name: Install PackageCloud CLI
        run: |
          sudo gem install package_cloud

      - name: Publish package to PackageCloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
          package_cloud push dniasoff/qcp-linstor-dev/ubuntu/${{ matrix.os }} $(ls ../*.deb)
