name: Build and Publish Linstor-server Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: ["jammy"]
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          python-version: '3.x'
    
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install python-linstor

      - name: Set up APT
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          devscripts \
          debhelper \
          dh-make \
          build-essential \
          libssl-dev \
          libxml2-dev \
          libcurl4-openssl-dev \
          libtool \
          autoconf \
          automake \
          libglib2.0-dev \
          python3-dev \
          python3-setuptools \
          python3-pip \
          coccinelle \
          fakeroot \
          dkms \
          cargo \
          rustc \
          keyutils \
          xsltproc \
          help2man \
          dh-python \
          docbook-xsl \
          python3-all \
          equivs \
          aspcud \
          dh-virtualenv \
          debmake \
          default-jdk-headless \
          unzip \
          gradle

      - name: local LINSTOR API Py repository
        run: |
          cd src/linstor-api-py
          make  || true  
          python3 setup.py build
          sudo python3 setup.py install
    
      - name: local LINSTOR Client
        run: |
          cd src/linstor-client
          PYTHONPATH="../linstor-api-py:." python3 setup.py build_man
          sudo python3 setup.py install
          
      - name: Check version.properties file
        run: |
          if [ ! -f src/linstor-server/version.properties ]; then
            echo "version.properties file is missing"
            exit 1
          fi
      - name: local Build LINSTOR Server
        run: |
          cd src/linstor-server
          ./gradlew getProtoc versionInfo --info

      - name: Build LINSTOR Server package
        run: |
          cd src/linstor-server
          dpkg-checkbuilddeps || (echo "Install unmet build dependencies first" && exit 1)
          dpkg-buildpackage -us -uc -b || (cat debian/rules && exit 1)
  
      - name: Install PackageCloud CLI
        run: |
          sudo gem install package_cloud

      - name: Publish package to PackageCloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
         package_cloud push https://packagecloud.io/dniasoff/qcp-linstor-dev/package/ubuntu/${{ matrix.os }} src/drbd/*.deb
